export default function Head() {
  return (
    <>
      <title>PANAVERSE DAO</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://i.ibb.co/PZZK5jn/Logo-png.png" />
    </>
  )
}
